"""transaction and provider fixes3

Revision ID: 130188c5ac25
Revises: 9872e89e9870
Create Date: 2021-06-20 09:59:54.657761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '130188c5ac25'
down_revision = '9872e89e9870'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
