"""transaction and provider fixes

Revision ID: 376206cd2d81
Revises: 7da9957ef42d
Create Date: 2021-06-20 09:48:29.514282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '376206cd2d81'
down_revision = '7da9957ef42d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
