"""rfid_uuid in users

Revision ID: 397948fc531a
Revises: 130188c5ac25
Create Date: 2021-06-20 10:43:42.144207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '397948fc531a'
down_revision = '130188c5ac25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('rfid_uuid', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'rfid_uuid')
    # ### end Alembic commands ###
