"""balance defaults to 0

Revision ID: 9382167d78eb
Revises: 6593f13ad865
Create Date: 2021-06-20 02:09:08.631553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9382167d78eb'
down_revision = '6593f13ad865'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
