"""transaction and provider fixes

Revision ID: 9872e89e9870
Revises: 376206cd2d81
Create Date: 2021-06-20 09:56:10.321160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9872e89e9870'
down_revision = '376206cd2d81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
